S05 us28 contact view
WildCodeSchool/orleans-php-2003-project-coachpeter pull request #212
Opened 2020-07-06 09:39 UTC by kodev-sudo

2020-07-06 10:09 UTC, Emmanuelle-Mendels submitted a review, later dismissed
ok

2020-07-06 11:45 UTC, sblondeau requested changes

2020-07-06 11:45 UTC, sblondeau commented on src/Controller/ContactController.php
> +            $dataForm = $_POST['contact'];
erk, non ! pas de $_POST dans symfony, never !
tu devrais
- creer une entity Contact (sans annotation @ORM car pas relié à une BDD)
du coup tu fais un $contact = new Contact; 
et 
          $form = $this->createForm(ContactType::class, $contact);

puis ensuite si ton form isSubmitted tu as ton $contact hydraté avec les données du form !

2020-07-06 11:45 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->html('<h3>Une nouvelle personne vous a contacté par le biais du formulaire de contact :</h3>
vaut mieux créer une vue twig et charger la vue ici avec $this->renderView

je vais sans doute montrer justement tout ça en livecoding demain

2020-07-06 11:45 UTC, sblondeau commented on src/Form/ContactType.php
> +                'required'   => true,
pas besoin de préciser required à true, c'est la valeur par défaut.

2020-07-06 15:55 UTC, Emmanuelle-Mendels approved these changes
ok

2020-07-07 08:04 UTC, sblondeau approved these changes

2020-07-07 08:04 UTC, merged