S06 us40 membre voir programmes affectés
WildCodeSchool/orleans-php-2003-project-coachpeter pull request #219
Opened 2020-07-06 20:46 UTC by Philippe-Naveilhan

2020-07-07 06:39 UTC, malyadev commented on src/Controller/MemberController.php
> +            'attendeds' => $user->getAttendeds(),
ptite faute d'orthographe, y'a pas de s aux verbes en ed ^^

2020-07-07 06:39 UTC, malyadev commented on templates/member/index.html.twig
> +        {%  for attended in attendeds %}
après je comprend que ce soit pour ça...

2020-07-07 08:15 UTC, Emmanuelle-Mendels submitted a review, later dismissed
ok

2020-07-07 10:06 UTC, sblondeau requested changes

2020-07-07 10:06 UTC, sblondeau commented on templates/member/index.html.twig
> +                    {{ programStep.title }} => accès valide <br>
hum, la mise en page est pas un peu trop "basique" là ? au moins un ul/li ou des cards ?

2020-07-07 10:13 UTC, Philippe-Naveilhan commented on templates/member/index.html.twig
> +                    {{ programStep.title }} => accès valide <br>
C'était de la micro-PR :baby:

2020-07-08 06:27 UTC, malyadev approved these changes
ok

2020-07-08 06:55 UTC, sblondeau approved these changes

2020-07-08 06:56 UTC, merged