FIX_Contact_Message #282
WildCodeSchool/orleans-php-2003-project-coachpeter pull request #311
Opened 2020-07-14 08:26 UTC by kodev-sudo

Removing space for Message input

2020-07-14 09:07 UTC, malyadev requested changes

2020-07-14 09:07 UTC, malyadev commented on src/Form/ContactType.php
> +                        "Je suis intéressée par votre programme. Auriez-vous plus d'informations à me communiquer ?"],
intéressé(e)

2020-07-14 09:10 UTC, kodev-sudo commented on src/Form/ContactType.php
> +                        "Je suis intéressée par votre programme. Auriez-vous plus d'informations à me communiquer ?"],
Les placeholder des précédents input : Nom : Sandrine
Nom : Germain

2020-07-14 17:40 UTC, Philippe-Naveilhan approved these changes
Approved

2020-07-15 06:51 UTC, sblondeau approved these changes

2020-07-15 06:51 UTC, merged