Errors navbar
WildCodeSchool/orleans-php-2003-project-coachpeter pull request #379
Opened 2020-07-20 21:14 UTC by malyadev

pages d'erreur avec affichage de la navbar allégée

2020-07-21 06:56 UTC, Philippe-Naveilhan requested changes

2020-07-21 06:56 UTC, Philippe-Naveilhan commented on templates/security/login.html.twig
>              </div>
Aouch ! la fatigue ! "Voues" / "idantifiant" :)

2020-07-21 06:56 UTC, Philippe-Naveilhan commented on templates/bundles/TwigBundle/Exception/error401.html.twig
>              <h1 class="text-center ">Oops ! Une erreur 401 est survenue...</h1>
Je me demande si on ne ferait pas mieux de mettre autre chose que 404-401-500...
"La page que vous demandez n'existe pas... Ne quittez pas, un opérateur va vous rediriger... La page que vous demandez n'existe pas... Ne quittez pas, un opérateur va vous rediriger... La page que vous demandez n'existe pas... Ne quittez pas, un opérateur va vous rediriger... "

2020-07-21 08:52 UTC, Emmanuelle-Mendels submitted a review, later dismissed

2020-07-21 10:32 UTC, sblondeau requested changes

2020-07-21 10:32 UTC, sblondeau commented on assets/scss/errorPages.scss
> +    background-color: rgba(0, 56, 79, 0.85);
variable CSS

2020-07-21 10:32 UTC, sblondeau commented on templates/bundles/TwigBundle/Exception/error401.html.twig
>              <h1 class="text-center ">Oops ! Une erreur 401 est survenue...</h1>
je suis d'accord
plutot que "404" ou "500" mettez
"Cette page est introuvable"
"Une erreur est survenue"
"Vous n'avez pas l'autorisation d'accéder à cette page"...

2020-07-24 08:27 UTC, Emmanuelle-Mendels approved these changes
ok

2020-07-24 09:20 UTC, sblondeau approved these changes

2020-07-24 09:20 UTC, merged